### ISSUE TITLE
Hide soft buttons

### ISSUE THREAD

**Issue by lenisko** [raulhaag/MiMangaNu#105]
Hello,
Please hide software buttons while reading. They are annoing.

**Comment by Johndeep** [comment]
Are you referring to phones without hardware buttons like the Nexus, where Android putting up "on screen" home/back buttons (which would be possibly those software buttons you spoken of)?

**Comment by lenisko** [comment]
There is a thing called immersive mode.

Take a look here https://github.com/L-Henke/secrecy/commit/e8bb2192b8715f5ab09510ecdc23d572065048fc

**Comment by raulhaag** [comment]
i go to see if i can implement to the next version (i only can test it on vm) 
show & hide go to be like the actual menu

**Comment by lenisko** [comment]
Sure, I can always test it.

**Comment by raulhaag** [comment]
inmersive mode only works on android >= kitkat 4.4 (working in vm)
fullscreen on earlys versions android documentation says:
There is a limitation: because navigation controls are so important, the least user interaction will cause them to reappear immediately. When this happens, both this flag and SYSTEM_UI_FLAG_FULLSCREEN will be cleared automatically, so that both elements reappear at the same time.

**Comment by lenisko** [comment]
Well that's why it should be in options, so users can enable/disable it.
Some note about working only on >4.4 and everything will be fine.

But well, yeah... it should be added. It's really a pain to see those buttons in gallery-like application those days.

**Comment by raulhaag** [comment]
automatic detect version and on center tap hide or show navigation bar 
so that is ready for next version i go to push now

**Comment by raulhaag** [comment]
automatic detect version and on center tap hide or show navigation bar 
so that is ready for next version i go to push now

**Comment by lenisko** [comment]
Can't wait for it, thanks!

**Comment by lenisko** [comment]
Good work!
