### ISSUE TITLE
Can't download manga chapter

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#109]
I can't download the chapter 64 from hello helper on kissmanga even after deleting the manga and redownloading it, the last chapter never start to load

**Comment by Johndeep** [comment]
Okay, we really need something like a log or something which at least logs error and save it into a file.. this is getting ridiculous difficult to reproducing the error..

Hmm, I also can't get the 64th chapter of Hello Hellper though.. I suspect it's because of the name "Blood Ocean ①", the 1 with circle screws up the string comparison. But I'm not sure.

Can you try some other mangas with those strange chapter names? Just in case.

**Comment by Dostoi** [comment]
By randomly opening manga page I managed to find another one which has the same issue
http://kissmanga.com/Manga/Shinohayu-The-Dawn-of-Age

**Comment by Johndeep** [comment]
Oh, seems to hit the bull's eye.. hmm, that's why I couldn't download some chapters from some mangas too.. haha (damn unicode names) :sweat_smile:

Let's see how my exploring of that part of the code jungle will go, maybe raulhaag will fix this. But either way, I afraid most likely not before the release of 1.34 or something higher than currently in f-droid though.

**Comment by Dostoi** [comment]
It's not an urgent problem anyway. Just wanted to give some feedback ;)

**Comment by raulhaag** [comment]
thath chars can be replace by nothing and work

**Comment by Johndeep** [comment]
What the heck? The entire name isn't even needed in the url, only the id.. wow.. that's strange.

**Comment by raulhaag** [comment]
for the next ready before the two releases whit errors :-(

**Comment by Johndeep** [comment]
@raulhaag How long you have to wait for f-droid normally?

**Comment by Johndeep** [comment]
Confirmed, chapters with special characters works! :smiley: :thumbsup:

**Comment by Dostoi** [comment]
Work perfectly :)
