### ISSUE TITLE
Hard to see the difference between read and unread

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#117]
It's kind of hard to see the difference between read and unread with the last update (especially if you didn't begin to read the next chapter).
Is it possible to put unread chapter in black as of now the chapter being read is blue (nice thing by the way) ?

**Comment by Johndeep** [comment]
Oh, this issue also interests me. would be nice, if it's grayed out or at least has marking (like Dosoi said).

**Comment by Johndeep** [comment]
If you mean the chapter, it's fixed with the current commit, I lighten up the read mangas, so it is easier to distinguish. Well, either way, you have to wait for f-droid to update.

But the currently version isn't quite ready, because I introduced some sorting and rearranged menus, while raulhaag added a dark theme, which isn't really ready (still some wrong colored spots).

So hopefully we can get this right soon. Have patient **or** just try the "bleeding edge" version yourself by compiling it yourself ;P

**Comment by raulhaag** [comment]
Johndeep advice me about the wrong colors i wanna push the new version before the sunday otherwise go to be after 14/9

**Comment by Johndeep** [comment]
Even if this isn't the right Issue, do you like the current color picker? Or should I just get back to a grid based color picker?

**Comment by Johndeep** [comment]
Well, the wrong colors are those with KitKat or lower, where the check box are black, even with black theme, but I don't know myself how to fix that. Maybe there are more.
From lollipop and later the colors should be correct, I hope.

**Comment by Dostoi** [comment]
Thanks for the fix :)
