### ISSUE TITLE
Translation 

### ISSUE THREAD

**Issue by Wabuo** [raulhaag/MiMangaNu#172]
Where is your translation stuff hosted or where are the files? I want to improve few of the German translations.

**Comment by Johndeep** [comment]
Did you check the current version of the translation? Because I already fixed some of the strange translation (probably because some new stuff were added).

But feel free to enhance it even further. You can usually find them in
MiMangaNu/app/src/main/res/ folder, the german translation is in values-de/string.xml.

If you don't already know, I strongly recommending to use Android Studio and its translation editor function.. it's just much easier and less error prone.

Viel Spaß dabei ;P

**Comment by raulhaag** [comment]
https://github.com/raulhaag/MiMangaNu/blob/master/app/src/main/res/values-de/strings.xml
but @Johndeep correct this to the next version, so check it
