### ISSUE TITLE
error with the download of manga

### ISSUE THREAD

**Issue by xken2x** [raulhaag/MiMangaNu#185]
when i add or update a manga, and i try download the new chapter/new manga, sometimes the down loader only mark error, no matter how you try, and is necessary reboot the app to can download the manga

**Comment by Dostoi** [comment]
Did you load a lot of chapter from the same site before ? (like an hundred )  Or a total of update checking close to that ?
Some site have a protection against ddos and block the app if you download too many things at the same time, see #148

**Comment by xken2x** [comment]
The problem is with servers as tmo an nm, than allow me un a previous versión of this app download all the chapters of mangas as naruto, gantz and one piece, without no mistake.
The error happens with all the servers, and not only with the mangas with most chapters, happens with the mangas with less of 20 chapters.
When i get back my laptop i will send a logcat of the app for you can see the problem

**Comment by xken2x** [comment]
And the error sometimes fix by itself when i update the avaliable chapters  of the manga o  restarting the app

**Comment by raulhaag** [comment]
test version 1.42 if httpOk fix it

**Comment by xken2x** [comment]
The error is with the versión 1.42 only, the 1.41 work fine

**Comment by xken2x** [comment]
When tge next versión come out?
Try to use de download code of the versión  1.41 pls, and add a persistent notificación on the system bar for the download progresos, this can be a good adition to the app

**Comment by digiwombat** [comment]
I'm also getting a lot of errors. Not sure if the issue is related but it's pretty much to the point that I can't use the app. 

Files fail almost 100% of the time. Even if the threshold doesn't csncel the download I csn usually expect at least one missing file.

These errors don't happen in other apps like MangaDLR or even Manga Watcher which is old and busted. I downgraded to 1.41 and still had the same issue. Downloads just fail. Msybe spoof a browser user-agent? No idea without looking at the code.

**Comment by xken2x** [comment]
I was having the same error as you, but i soved it unistalling the app, and erasing all about it, after reinstall the 1.41 versión and copy de db archive to restore your list of manga.
This work for me, dont forget backup the en archive before erase all about the app.

**Comment by digiwombat** [comment]
Hmm, I can't seem to get it to work any better. Though, I will say it seems odd to be using byte buffering rather than anything more direct like an async call to an inputstream with java.net. Or an image specific lib like AUIL.

I might do a quick fork tomorrow to test a few options out and report back.

**Comment by xken2x** [comment]
Ok, we will wait your results

Pd: the error can be by an error invthe database of manga, because un debug show me a error of address not found, and after i update the manga db and the app work.
I still in the 1.41 version

**Comment by digiwombat** [comment]
Okay, I had a bit of a break through, but it was in a way I wasn't expecting. I tried a few different download methods and was still getting errors. But really only with MangaHere.

I did a bit of looking and their CDN serves up the images with a version unix timestamp that corresponds to their upload date. If this timestamp is wrong or missing the file is served extremely slowly, possibly in some cases slow enough to trigger timeout errors.

If I am reading the regex correctly, this v= query string being stripped.

So far, I have not run into errors on other servers of this magnitude (after the reset xken2x suggested) but could be worth a look.

**Comment by raulhaag** [comment]
about this it mark as error after download few imges or before to start to download them?
if you can specifi server/manga/chapter to test

**Comment by digiwombat** [comment]
After a few images.

The server and manga I did my testing on is MangaHere (EN), Trash., Chapter 1.

I was using it because it has plenty of pages for testing reliability. The same manga on KissManga downloaded repeatedly without any issue at all, but failed pretty reliably on MangaHere after 4-8 pages.

**Comment by xken2x** [comment]
i reinstall the app and erase the database, the only server than have problems is mangahere and esmangahere, but i dont use these servers a lot, so i dont care.

**Comment by xken2x** [comment]
i will close this issue, and open other to mangahere and esmangahere
