### ISSUE TITLE
Add grid changer

### ISSUE THREAD

**Issue by M2ck** [raulhaag/MiMangaNu#204]
To allow users to choose how many manga display on a row, from 1 to 4 manga(s) max per row.

**Comment by xtj-9182** [comment]
it only took us a year but finally the technology is here !

**Comment by raulhaag** [comment]
@xtj-9182 can you add option if it 0 (as default) use automatic calculated?

**Comment by xtj-9182** [comment]
yes of course, I'm going to use 1 though since it's unused.

currently I'm struggling with the OnPreferenceChangeListener of the seekbar since somehow it won't trigger when I'm going from 1 to 2 which is important since I want to change the Summary text to "automatic detection" on 1 and change back on all other values. u.u
