### ISSUE TITLE
Being able to search a site database with more than one genre type

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#210]
Right now if you search a site database you can only search with one genre. 
It could be really great to be able to add more than one to have more precise search like some site allow to do in advanced search

**Comment by raulhaag** [comment]
im thinking on this long time ago, in fact to remake the server visual navigation, but when i think in all the modification needed to do this i leave it to other day

**Comment by Dostoi** [comment]
Maybe just having an advanced search menu that let you add more search option. Like having a + button somewhere in this menu that add search option when you press it

**Comment by raulhaag** [comment]
![filtrosmultiple](https://cloud.githubusercontent.com/assets/2048339/19899387/b74c0fee-a03e-11e6-9aab-a7e5a09098e8.jpg)
on the way just need to update other 20 servers :-P its go to take a time

**Comment by Dostoi** [comment]
Awesome !
There's nom way for only doing it once ?

**Comment by raulhaag** [comment]
No, but whit luck this weekend I finish this feature

**Comment by Dostoi** [comment]
I noticed that I can't check more than one genre, is it normal ?

**Comment by xtj-9182** [comment]
I have improvements coming for mangaeden sites + ninemanga. I'll add genre exclusion to these too, I can't promise about other sites tho.

**Comment by Dostoi** [comment]
No problem, it's already great what you're doing !

**Comment by xtj-9182** [comment]
finally someone that recognizes my awesomeness ^^;

I just looked at the KissManga code and I think I can make it work;

having said that there is a limitation on KissManga you can only apply an order (sort by Popularity, Latest Update etc ...) when you select a single genre. When you select multiple genres you CANNOT apply an order. This is how it works on their site as well.

I'm going to switch the buttons to multiple selection and if only one is selected then an order will be applied otherwise it will simply use the advanced search algorithm which won't allow for an order to be applied.

**Comment by xtj-9182** [comment]
Please test the new changes everyone.

**Comment by Dostoi** [comment]
My phone died a few days ago so I won't be able to help for a while ^^

**Comment by xtj-9182** [comment]
good finally you can get a new one xD
