### ISSUE TITLE
Bug - Before downloading check network connection

### ISSUE THREAD

**Issue by lenisko** [raulhaag/MiMangaNu#230]
Like in title, right now user can try to refresh list without network connection, it's pointless.

**Comment by xtj-9182** [comment]
there's a minor problem with this, from what I can tell it might not be easy to detect if a user is connected or not, for example the user might be using a vpn or 3g and we might not be able to detect that and then we deny the user to update his manga even though he is connected. 

For now I'm thinking about doing something like this:
we check if the user is connected and deny updates if he isn't 
then we add an option to ignore the network state which will enable the user to update anyway in case he is connected to a vpn or we failed to detect that he is connected for some other reason.

**Comment by lenisko** [comment]
Indeed it's just cosmetic issue. But we can always check error code or timeout for our connections.

**Comment by xtj-9182** [comment]
so do you think I should implement it or not ?

I'm a little concerned that checking the wifi state first might introduce a (possibly short) delay. However if we have an option to disable this behavior then it might be ok.

**Comment by lenisko** [comment]
worth try if you don't have anything else todo

**Comment by xtj-9182** [comment]
ok I work on it once I'm done with my current todo list.

**Comment by xtj-9182** [comment]
turns out there is a more elegant solution than I initially thought, and my initial concerns are completely gone. We simply use a broadcast receiver that notifies us once the wifi connection changes this seems to work pretty well in my tests. I didn't get around to test it on 3g yet but in case it doesn't work I also added an option to disable the receiver completely which reverts the app to behave as it originally did.

**Comment by lenisko** [comment]
good job :+1:

**Comment by xtj-9182** [comment]
there is a slight regression due to me and @raulhaag both working on something similar oops. Anyway when you lose connection right now while the update process is running it will take some time for the process to finish even though there is no connection since every generated thread still tries to connect even if the wifi connection is lost, anyway this will soon be fixed.

**Comment by lenisko** [comment]
Mhm got it, I'll report few more thing to check when I find time
