### ISSUE TITLE
Redownloading a picture make the reader go back a few pages

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#274]
With the last travis, when redownloading a page, the reader go back a few pages

With the last travis and the new reader.

**Comment by xtj-9182** [comment]
So recently I added a bounds check in the reloadimage function of the Reader class in hopes to fix https://github.com/raulhaag/MiMangaNu/issues/264. (I still don't know if that crash is fixed or not) Anyway from what I can tell even if I take out the bounds check I'm still experiencing weird behavior with the continuous reader. When I press re-download on a Fairy Tale chapter from MangaPanda the Reader will move a few pages forward, except if I'm on the first or last page, I have no idea why this happens. I hope @raulhaag knows something since I never worked much on the Reader ...

@Dostoi is there a travis build or stable release in which this is not happening ?

**Comment by raulhaag** [comment]
@Dostoi continuos o paged reader

**Comment by xtj-9182** [comment]
for me it's only happening on the continuous reader

**Comment by Dostoi** [comment]
Since a few version, but I didn't report it right away sorry

**Comment by raulhaag** [comment]
did someone test last travis?

**Comment by xtj-9182** [comment]
yep works for me.
