### ISSUE TITLE
Option to download next chapter if available while reading current chapter

### ISSUE THREAD

**Issue by sm7297** [raulhaag/MiMangaNu#279]
This option would be helpful if i am reading new manga from the start as it will automatically download next chapters in advanced. This option should also have number of chapter to be downloaded e.g. 3,5,10 or until the last chapter so, that reader dont have to wait.

**Comment by xtj-9182** [comment]
ok I implemented this. However I was lazy and only made it download the next chapter with no option to select the number of next chapters to download so that only one chapter will be downloaded at a time. I did this cause we already had a variable for the next chapter so it was trivial to implement. We might improve this in the future
