### ISSUE TITLE
Feature Request - Landscape Mode

### ISSUE THREAD

**Issue by fookitt** [raulhaag/MiMangaNu#316]
Using MiMangNu on my tablet, I notice I couldn't display 2 pages in landscape mode. Would be really nice to have that feature instead of being forced to use my big screen in portrait mode.

**Comment by raulhaag** [comment]
Try continuous reader it can do it well

El 28 jul. 2016 19:47, "fookitt" <notifications@github.com> escribió:

Using MiMangNu on my tablet, I notice I couldn't display 2 pages in
landscape mode. Would be really nice to have that feature instead of being
forced to use my big screen in portrait mode.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/raulhaag/MiMangaNu/issues/316>, or mute the thread

**Comment by raulhaag** [comment]
example
![menu](https://cloud.githubusercontent.com/assets/2048339/17247822/5830993e-556c-11e6-99a4-ce452cf965c1.jpg)
![lcr](https://cloud.githubusercontent.com/assets/2048339/17247824/5d8f781e-556c-11e6-9b42-e435a55401b5.jpg)

**Comment by sm7297** [comment]
it will be good to have and landscape mode in Always landscape(sensor) mode
