### ISSUE TITLE
SenManga and LeoManga seem broken

### ISSUE THREAD

**Issue by xtj-9182** [raulhaag/MiMangaNu#332]
LeoManga still allows searching for Manga but seems to show no cover images at all.
SenManga doesn't even allow searching for Manga.

**Comment by raulhaag** [comment]
senmanga start to work by itself, leomanga fixed, this weeken the release

**Comment by xtj-9182** [comment]
yeah I noticed that too, maybe my wifi was just weak.

**Comment by raulhaag** [comment]
No, when you reported was not working.

El 10 sept. 2016 12:58, "xtj-9182" <notifications@github.com> escribió:

yeah I noticed that too, maybe my wifi was just weak.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/raulhaag/MiMangaNu/issues/332#issuecomment-246119574>,
or mute the thread
