### ISSUE TITLE
Cancelling an update open the app

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#337]
If you cancel an update (manual or auto) it will open the app which is bothering especially with auto-update

With a build dating from a few days

**Comment by xtj-9182** [comment]
I think cancelling works but not always, for some reason the intent id which we use to 
know if we should cancel an update gets overwritten by the content intent id, this is why it will
open the app instead cause the id is different from the cancelling id, I haven't yet found out 
why the id sometimes gets overwritten ...

**Comment by xtj-9182** [comment]
update: damn I think I know why this is happening :(. I think it's caused by us expanding the searching for updates notification, instead of using a "normal" notification I think this is causing the cancel action from not working correctly. 

soo damn ... 

we could use a not expanded notification for updates,
but then we get no expanding when a title is too long
granted it's probably less important on the 
searching for updates notification. 
All other notifications are still expanded

**Comment by Dostoi** [comment]
It still opens the app and I can't cancel update now ^^
For the manual update at least

**Comment by xtj-9182** [comment]
yeah I just noticed I fixed the bug for the manual update only :/

but I have a new fix for this coming soon

**Comment by Dostoi** [comment]
Great ! :)

**Comment by Dostoi** [comment]
Canceling an update still open the app. Not sure if I was clear with open the app.
Like if you launch an update, leave the app but not close it (leave it runing in the background but having another app in the foreground), and click on cancel, the app will come to the foreground and put the app you were using in the background
