### ISSUE TITLE
Some chapters are duplicated

### ISSUE THREAD

**Issue by wyrex** [raulhaag/MiMangaNu#342]
Sometimes after update this happens.  Original chapters retain their read pages count but new ones appear. It only happens sometimes. 

http://imgur.com/xprtP37

**Comment by xtj-9182** [comment]
sometimes the admins from the manga websites from which we get our information will rename or re-add previously added chapters, sometimes these "updated" chapters contain new images (as in better resolution or cleaner) sometimes they just rename the old chapters for no reason.

Someone once suggested that we could potentially mark chapters with an update icon instead of showing the new chapter when this happens . (see https://github.com/raulhaag/MiMangaNu/issues/229)

I'm currently a little busy so I can't work on this but if anyone is willing to work on this patches welcome :D

**Comment by raulhaag** [comment]
@wyrex server?, becouse a version or two ago i note a problem with a server (don't remember MP or MH or MF), sometimes its give the http://xxxxx/x/xx/ and others http://xxxxxx/x/xx and them duplicates appear, fixed on last but if you have to update those first update this can happens. I sugest select all chapter and remove and then make the update (Full) for the manga

**Comment by wyrex** [comment]
@raulhaag mostly MangaFox.

**Comment by raulhaag** [comment]
closed if happend againg with series added on db after november/2016 re open it
