### ISSUE TITLE
Making the "mark all manga as read/unread" faster

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#350]
Marking all chapter as read/unread can be long sometimes for manga with a lot of chapter even when it shouldn't, like when there's only a few chapter needed to be changed.

I looked a bit and I think it's because you change the chapter state for every chapter and not only those who need to be changed.
I was wondering if it was possible to create two "subtables" for the chapter table. One containing the read chapter and the other the unread one. So you don't have to change the whole chapter table but only a part of it by changing the corresponding "sub" table.

I'm not doing it myself because I'm not used to android developing yet but I'll try to help in the future ;)

Edit 1: But I'm wondering if it won't make it longer in some case as you have to switch values from table

**Comment by xtj-9182** [comment]
> Marking all chapter as read/unread can be long sometimes for manga with a lot of chapter even when it shouldn't, like when there's only a few chapter needed to be changed.

please clarify if you mean "Mark all as (un)read" or you selected all chapters and then used "Mark Selected as (un)read". "Mark all as ..." are pretty much instantaneous. The "Mark Selected as ..." functions are slower. (even after having multithreaded them)

> I looked a bit and I think it's because you change the chapter state for every chapter and not only those who need to be changed.

no. I made sure that we specifically only change chapters that need to be changed.
"Mark selected as read" specifically checks if chapters are already read and ignores those. Same for unread chapters for "Mark Selected as unread".

> I was wondering if it was possible to create two "subtables" for the chapter table. One containing the read chapter and the other the unread one. So you don't have to change the whole chapter table but only a part of it by changing the corresponding "sub" table.

I think this is not useful since we can already know the read status of a chapter by checking:
`getReadStatus()`
which we are already doing. Switching values from two different tables would probably be slower.

If you are really talking about the "Mark all as ..." functions then I'm a little confused cause these are instant on my device, and therefore don't use any special checks. It would be trivial to add the same checks for the mark all as functions but I'm doubtful if that would do anything these functions are pretty much instant on my device even when I use Hajime no ippo as manga.

> I'm not doing it myself because I'm not used to android developing yet but I'll try to help in the future ;)

this sounds very good :+1:  when I started out I only clarified the meaning of some strings and then I removed some unused strings that I could detect with android studio xD good times. Programming is also pretty easy, just read some tutorials or look for some ebooks online there are a lot of resources, most are not android specific but android adds only little and that is easy to learn about I would say. The most important part is that EVERYTHING needs a context ugh ...

**Comment by Dostoi** [comment]
> Marking all chapter as read/unread can be long sometimes for manga with a lot of chapter even when it shouldn't, like when there's only a few chapter needed to be changed.
If you use the option of a manga "Mark all chapter as (un)read".

> If you are really talking about the "Mark all as ..." functions then I'm a little confused cause these are instant on my device, 
I think my phone is dying, it takes way too long for only 3 chapter sometimes ^^ . 

The update isn't done in Database.java ? The function "markAllChapters"
Because if that's the one, it doesn't check if it's already read or not, it write for the whole column, so the whole table
 if (!database.isReadOnly()) {
                database.update(TABLE_CHAPTERS, cv, COL_CAP_ID_MANGA + " = " + mangaId, null);

**Comment by xtj-9182** [comment]
yes that's true, I was talking about the mark selected as functions, I really thought you just mistook them.

it is of course true that mark all as functions uses one table. but I'm baffled how that can't be instant on your device. compared to mark selected as functions the mark as functions just execute a simple db statement instead of going through a slow for loop. there is an added SortAndReload chapters though that isn't executed for the mark selected as functions. you should look at the MarkAllAsRead() async classes

if you can come up with optimization for slower devices that would of course be great

**Comment by xtj-9182** [comment]
@Dostoi 
Any new ideas ?

I'm not really sure what I could do to improve this.

**Comment by Dostoi** [comment]
No, but i think it's really just my phone dying so don't bother ^^

**Comment by xtj-9182** [comment]
I suggest getting a new one. I don't know how people can use old phones anyways since usually new android versions are dope as fuck and come with all these new features :D.

I'm closing this then.
