### ISSUE TITLE
Search by last update, most popular in server list

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#358]
Before the last update we could search by last update, most popular and so on in the server manga list but we can't anymore.
Is it planned to add it again ?

**Comment by raulhaag** [comment]
Advance search don't have this option,if I'm wrong tell me and I will add it

**Comment by raulhaag** [comment]
i go to roll back multifilters on this two just becuase many devices can't handle the full list at once

**Comment by Dostoi** [comment]
Maybe putting a 2nd search menu, like before ?
Being able to sort by last updated or new manga was a nice feature

**Comment by Dostoi** [comment]
Same here ^^

**Comment by Gomgoru** [comment]
On Nov 12, 2016 1:43 AM, "Dostoi" <notifications@github.com> wrote:
>
> Maybe putting a 2nd search menu, like before ?
> Being able to sort by last updated or new manga was a nice feature
>
I'd like to add my vote for this too. I read my manga in “last updated”
order (otherwise I forget to read some of them for several months ;-) … yes
I know I have way to many in my list! But my list “To Be Read” is 10×, or
more, as long and its not on MiMangaNu … maybe I should add a requested
function to MiMangaNu for a “Interested In” list. A list that is shown and
can be selected from to add to the regular directory of reading mangas?

Thanks,
Gomgoru

**Comment by raulhaag** [comment]
@Gomgoru now mmn preserve that order
@Dostoi  may be in future i will add diferente menu for more filters

**Comment by Dostoi** [comment]
No need, I just didn't have the last travis with the menu fix :)
