### ISSUE TITLE
[MangaFox]Last page not found in any manga and chapters

### ISSUE THREAD

**Issue by faan11** [raulhaag/MiMangaNu#389]
I follow some manga in Mangafox website. In each manga, the number of pages isn't correct.
The last page is not detected. 
For example, in the website the chapter has 30 pages. In the mobile application has 29 pages. I tried to use another manga in the mobile using a different website and the number of pages detected was correct.

SO used:Android 5.0.

**Comment by raulhaag** [comment]
A time ago the last page was used to comments only, if that changed i can
be fixed easy

El 27 ene. 2017 14:14, "Fabio Pagnotta" <notifications@github.com> escribió:

I follow some manga in Mangafox website. In each manga, the number of pages
isn't correct.
The last page is not detected.
For example, in the website the chapter has 30 pages. In the mobile
application has 29 pages. I tried to use another manga in the mobile using
a different website and the number of pages detected was correct.

SO used:Android 5.0.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/raulhaag/MiMangaNu/issues/389>, or mute the thread

**Comment by raulhaag** [comment]
ready
