### ISSUE TITLE
Unable to select SD Card for download location

### ISSUE THREAD

**Issue by amdemas** [raulhaag/MiMangaNu#390]
Using Fire OS I am unable to select the sd card(sdcard1) for use with storing downloads. It returns "unwritable folder" and it seems the "Move to SD Card" option in settings is greyed out. Is this something that could be put into the next update?

**Comment by raulhaag** [comment]
Hi, since android kitkat some android distribution lock sd card write access but if you create on the sd card the folder Android/data/ar.rulosoft.mimanganu/ and select this as download location you can use it.
Try it and tell me if work in Fire os (i think it give permission in the same way to write folder), about move to sd the app only have 5mb and let me think about it.

**Comment by amdemas** [comment]
That worked! Thanks

**Comment by raulhaag** [comment]
good to know.
