### ISSUE TITLE
External manga filters/parser file

### ISSUE THREAD

**Issue by lenisko** [raulhaag/MiMangaNu#415]
Just an idea, what do you think about creating one file with all manga servers definitions, filter and parser informations etc... ?
I guess this won't be easy to implement but would resolve need to upgrade whole application when something is getting changed, this way we would need to upgrade filters definitions only.

**Comment by raulhaag** [comment]
looks good on teory but really complicated to implement, if you know any java open source to see, using this kind of external plugin give me the link,  just to analyze the viality of adding it.

**Comment by lenisko** [comment]
I'm not Java specialist and I know nothing about Android programming as well but in normal case I would do it like:
- Move all logic to application itself, like MangaServerProcessor class with a loot methods to use and then sync only regex, urls, instructions which methods and in which order should get fired etc... 
- Use some scripting engine to parse those lists from inside of application
- Use some kinda eval I think there's something like ScriptEngine in Java (but this might be heavy)

There might be a better solution but I don't know Java/Android.

**Comment by xtj-9182** [comment]
If I understand it correctly you're basically proposing some kind of plugin system in which servers are plugins.

Even with such a system the app itself would still need to be updated every now and then due to internal logic changes that have nothing to do with the server logic.

> Move all logic to application itself, like MangaServerProcessor class with a loot methods to use and then sync only regex, urls, instructions which methods and in which order should get fired etc...

This I think might be a problem since some websites have their own quirks and it might be harder to work around these quirks by having to follow some established parsing standards.

There might be some benefits to this but there are downsides too.
