### ISSUE TITLE
Issues with Manga Fox

### ISSUE THREAD

**Issue by AxezCore** [raulhaag/MiMangaNu#455]
Started a while back that it wouldn't load the popular list, but you can still access and search the alphabetical list. A few days ago it began returning an error when trying to download a new chapter, and refreshing the download just queues it indefinitely.

**Comment by tempura-san** [comment]
Which version do you run? The issue with MangaFox (and MangaHere) should be fixed with version 1.70.
I assume you have installed the app using F-Droid, so you will need to wait a bit. F-Droid is currently at version 1.69 but should pick up 1.70 soon.

If you can't wait, you could use the version from the GitHub release page - but beware, if you have installed the app via F-Droid, you would need to reinstall it, as the signature keys do not match (see https://f-droid.org/docs/FAQ_-_App_Developers/#what-about-signing).

**Comment by AxezCore** [comment]
I am using f-droids version, guess i'll wait a couple of days and see what happens.
