### ISSUE TITLE
"Could not load page count" on MangaHere

### ISSUE THREAD

**Issue by Vitelia** [raulhaag/MiMangaNu#481]
As the title says, since a few days (two at most) when trying to download a manga from MangaHere, it doesn't even start, claiming "Could not load page count" (despite not having problems loading the list of chapters).

From the servers i usually read, it's the only one with that error at the moment.

Checked again right now in v1.73 installed from Fdroid (updated today from v1.72)

PS: this problem came out of nowhere while i was using the app and forced me to continue reading from other server xD so i think it may be something related with a change in the website.

**Comment by tempura-san** [comment]
You are right - there has been a change in the page layout (the 'featured' page was added). As the 'featured' page fails to parse as an integer, you get this error.

@raulhaag This is fixed in #478 by [this commit](https://github.com/raulhaag/MiMangaNu/pull/478/commits/13a09df3538f383e4962b656582f3fdb7b6a78c9).

Nevertheless thanks for reporting!

**Comment by fushark** [comment]
I take it this is also the same problem with mangatown. I hope this is solvef with that commit as well. Thx for a good app and quick response.

**Comment by tempura-san** [comment]
Yes, it is. Mangatown is fixed with [this](https://github.com/raulhaag/MiMangaNu/commit/c9d86e911a515d08255e602358de3a22461b919d) commit which was part of #478. As the pull request is now in the master branch both servers should work again in version 1.74.
