### ISSUE TITLE
Can you please add an option to zip the chapters

### ISSUE THREAD

**Issue by patraanjan23** [raulhaag/MiMangaNu#491]
There is this problem when I want to share some image I open the share gallery and I've full page filled with downloaded manga chapters. It'd be really cool if you just add an option to keep the chapters in a zip or something that can't be recognised by the Android framework as image. I know there is an option to hide image from gallery but I don't think it works when I'm trying to share an image from the gallery. Please consider this a quality of life improvement.

**Comment by Dostoi** [comment]
There is already an option to hide downloaded pages from the media gallery. It's the first option, at the top of the option menu.

**Comment by patraanjan23** [comment]
I'm attaching two screenshots to say that it is not working if that's what
it's supposed to be doing.

On 28-Nov-2017 13:17, "Dostoi" <notifications@github.com> wrote:

There is already an option to hide downloaded pages from the media gallery.
It's the first option, at the top of the option menu.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/raulhaag/MiMangaNu/issues/491#issuecomment-347440481>,
or mute the thread

**Comment by patraanjan23** [comment]
I'm attaching two screenshots to say that it is not working if that's what
it's supposed to be doing.


![screenshot_20171128-174309](https://user-images.githubusercontent.com/6746015/33319390-8477d908-d464-11e7-87d0-59f8b86b5b02.png)
![screenshot_20171128-174340](https://user-images.githubusercontent.com/6746015/33319391-84aa8e52-d464-11e7-8bdf-1fe42da063e5.png)

**Comment by tempura-san** [comment]
I'm not sure if the toggle button is in **on** state by default after installation. IIRC I had a similar issue back when installing MiMangaNu the first time.

The creation of the `.nomedia` file in the image directory is triggered on changing the preference slider from **off** to **on** (see `PreferencesFragment.java`).

So could you please:
* toggle the slider from **on** to **off** and back to **on**
* restart your phone/tablet to have the Android tracker remove the images from its cache - might take some time even after restarting

Now the images should not longer show up the gallery. Please let me know if that worked for you.

**Comment by patraanjan23** [comment]
@tempura-san that worked. I think the problem was that I never toggled that setting cause I thought it was on by default. I think the toggle button has a bug.

**Comment by raulhaag** [comment]
Yes i need to change this to unchecked as default,  about zip i'm not sure
about the performance and capabilities.

**Comment by tempura-san** [comment]
IMHO a better way would be to create the `.nomedia` file at the first run when the `MiMangaNu` directory is created - as most people would not want the Manga pages to show up in the gallery (my guess). 

Also (or as an alternative) I would suggest to have the initial state of the switch when opening the preferences depending of the presence of the `.nomedia` file - not on the stored preference itself, as both may diverge (on first start and also in case the Manga directory is changed/relocated).

If you agree, I could prepare a change for the latter.

Concerning the ZIP: as it is considered a workaround for this issue, I would drop the idea ATM as the fix is needed in a different place. Except if you plan to support CBZ files in the future. Personally I do not see a strong need for it.

**Comment by raulhaag** [comment]
Please do it, I'm not going to have my computer since Monday

**Comment by patraanjan23** [comment]
@tempura-san the zip feature can be an experimental or optional feature. I think it's better than creating one folder for every chapter. Also that cbz support can be a good thing.

**Comment by tempura-san** [comment]
@raulhaag, @patraanjan23 The PR should fix the consistency between the preference and the real world existence of the `.nomedia` file. It should be WYSIWYG now. :smile: 

@patraanjan23 I understand that it would look better, but for the functionality of MiMangaNu it would make no difference. Also the savings due to compression would be minimal, as the images are usually already compressed well.
For CBZ (if really needed) the shortest route would be to add an import functionality similar to the **FromFolder** 'server'.
Nonetheless most people use the app to conveniently fetch Manga from various online sources, so I don't know how many people would go for the offline route...

**Comment by patraanjan23** [comment]
@tempura-san okay then mark this issue solved. Thanks for quick handling of the issue.

**Comment by tempura-san** [comment]
You're welcome. Please leave the issue open until the merge request is accepted and released.
