### ISSUE TITLE
Problemas con tumangaonline.com

### ISSUE THREAD

**Issue by marrokin** [raulhaag/MiMangaNu#492]
No se pueden descargar capitulos desde 
[https://www.tumangaonline.com/](https://www.tumangaonline.com/)

**Comment by raulhaag** [comment]
Si lo note está mañana pero hasta el lunes no estoy en casa y de ahí la
actualización

El 1 dic. 2017 13:49, "Edwin Marroquin" <notifications@github.com> escribió:

No se pueden descargar capitulos desde
https://www.tumangaonline.com/

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/raulhaag/MiMangaNu/issues/492>, or mute the thread

**Comment by raulhaag** [comment]
lista en v1.75 recien salida
