### ISSUE TITLE
Problem with the database and the 1.76

### ISSUE THREAD

**Issue by tom2411** [raulhaag/MiMangaNu#501]
I just install the 1.76 version and when I launch the app my database was empty.
I try to change the path but it do nothing could you help me please ??

**Comment by raulhaag** [comment]
Last version make a couple of changes in databases tables, this take a time if you force the app close in this process you can lose a couple of data about chapters, if you send me the db i can try to do the update in the emulator, i need to know wath android versio you have

**Comment by raulhaag** [comment]
[app-release.zip](https://github.com/raulhaag/MiMangaNu/files/1583678/app-release.zip)
please extract and test this version if corrects update your database to post a new release whit this change

**Comment by tom2411** [comment]
It don't work with the release.

**Comment by tom2411** [comment]
I'm on android 7.0

**Comment by tom2411** [comment]
I did a test 
I download a japscan manga to see where it will goes and it goes at the same place than the other but in mimanganu I can see just the manga that I downlaod.

**Comment by raulhaag** [comment]
at this time you already created a new db when you add a new manga

**Comment by tom2411** [comment]
So what can I do ??

**Comment by tempura-san** [comment]
Unfortunately - as far as I understand - at this point not much, besides starting over in case you do not have a backup at hand.

@raulhaag As an improvement a backup of the DB file could be created before doing the DB update? So for such cases a backup could be available. Furthermore some progress message for when the update is running to notify the user to not interrupt the process (i.e. close the app).

**Comment by tom2411** [comment]
So can I hope that you plan a backup system ??

**Comment by tom2411** [comment]
For the next version ??

**Comment by tempura-san** [comment]
Writing a "backup system" (which would cover all eventualities) would be a bit far-fetched for a simple app. Besides, IMHO it is the user's responsibility to keep a backup of important data. Your device may crash any time and data may always be lost.
MiMangaNu does not hide its database in `/data`, so it is easy to copy the `MiMangaNu/dbs` folder to some save location from time to time in case of need.

Nonetheless #502 implements creating a backup (=copy) of the DB before doing `onUpgrade`. The file is placed alongside the original DB with the suffix `.bak`. In case of DB corruption **due to an upgrade**, the user can copy the backup over the corrupted one and try again. Keep the backup, in case the app itself has some issues - it would screw up the restored file as well.

The backup is **not updated on any other occasion** besides upgrading, so it may become out of date quickly for other scenarios.

@raulhaag I have tried to figure out how to display a notification in case of an upgrade. Unfortunately anything I try to show pops up too late (as the splash screen is active at the time the DB is opened the first time and showing seems to be delayed until the `MainActivity` is in sight). TBH I'm not too deep into Android how to proceed - maybe you have an idea.

Anyway - happy holidays! :wave:

**Comment by faan11** [comment]
IMO an interesting feature would be to sync the database online instead of offline back up.

Happy holidays :)

**Comment by tom2411** [comment]
Can you update the version on F-Droid ??

**Comment by tom2411** [comment]
Please

**Comment by tempura-san** [comment]
@faan11 What do you mean by online? Google Drive? Might be interesting, but I haven't used it up to now.

I for my part use Syncthing on all my devices to sync them my local server. That way synchronisation happens in the background as soon as I am at home. If I wanted to, I could do versioned backups as well.
I never use any cloud backup solutions as I like to remain the owner of my data. :wink:

**Comment by faan11** [comment]
@tempura-san Yeah why not, Dropbox, Google drive, Mega (better), ftp etc.
I never tried Syncthing for android data app sync. I will try.
Anyway I like the idea of a "export and import feature" in a common format like json. It improves the interoperability between different systems and different app version. ( also for a future possible integration with desktop ).

**Comment by tempura-san** [comment]
An export/import feature could simplify the scenario as in #503.

Basically all the data from the external storage directory (database, imaged optionally) and the preferences (e.g. as you have suggested as JSON) could be zipped and saved and restored on demand.

If you like, you could open a separate issue and add this functionality as feature request so the thought won't get lost.

**Comment by tempura-san** [comment]
@tom2411 It seems, that there is an issue in case you have Manga from MangaHere in your list. See my comment on the referenced commit for more details.
